import { default as axios, default as Axios } from 'axios';
import Head from 'next/head';
import Pusher from "pusher-js";
import styles from '../styles/Home.module.css';
import React, { useEffect, useRef, useState } from 'react';

export default function Home() {

    const [messages, setMessages] = useState([])
    const userRef = useRef()

    async function handleSendMessage(e) {
        e.preventDefault()
        const user = userRef.current.value
        await axios.post('http://localhost/api/post-message', { user }).then(response => {
            console.log('posted')
            // console.log(messages)
        }).catch(error => {
            console.log(error)
        })
    }

    useEffect(() => {
        Axios.defaults.baseURL = process.env.REACT_APP_API_BASE_URL;

        const pusher = new Pusher('a1091d9e1a6ed6652372', {
            cluster: 'us3',
            encrypted: true
        });
        const channel = pusher.subscribe('public.room');

        channel.bind('message.new', (data) => {
            setMessages(oldMessages => [...oldMessages, data])
        })
        return () => {
            pusher.unsubscribe('public.room')
        }
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>

                <div>
                    {
                        messages.map(msg => <><h1>{msg.user}</h1><p>{msg.createdAt}</p></>)
                    }
                    <form onSubmit={(e) => handleSendMessage(e)}>
                        <input
                            type="text"
                            placeholder="Set your username"
                            ref={userRef}
                            required
                        />
                        <div>
                            <button onClick={(e) => handleSendMessage(e)}>Send</button>
                        </div>
                    </form>
                </div>

            </main>


        </div>
    )
}
