import axios from 'axios';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import PublicMessagesPage from './components/PublicMessagesPage';
export default function Home() {
  const handleSendMessage = async (e) => {
    await axios.post('http://localhost/api/post-message').then(response => {
      console.log(response)
    }).catch(error => {
      console.log(error)
    })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <button onClick={handleSendMessage}>Send Message</button>

        <PublicMessagesPage />
      </main>


    </div>
  )
}
