import axios from 'axios';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import PublicMessagesPage from './components/PublicMessagesPage';
import {useEffect} from "react";
import Axios from "axios";
import Pusher from "pusher-js";

export default function Home() {
    const handleSendMessage = async (e) => {
        await axios.post('http://localhost/api/post-message').then(response => {
            console.log(response)
        }).catch(error => {
            console.log(error)
        })
    }
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>

                <PublicMessagesPage/>

            </main>


        </div>
    )
}
